# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-03 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_monthjournal'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthjournal',
            name='var1',
            field=models.BooleanField(default=False),
        ),
    ]
