# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-03 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_monthjournal_var1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthjournal',
            name='student',
        ),
        migrations.DeleteModel(
            name='MonthJournal',
        ),
    ]
