# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-14 09:34
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20170814_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='group',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='test', chained_model_field='test', null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Group'),
        ),
        migrations.AlterField(
            model_name='result',
            name='student',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='group', chained_model_field='group', on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
    ]
