# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-23 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_auto_20170814_1005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Exam',
        ),
    ]
