# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-23 20:31
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_auto_20170823_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='test',
            new_name='exam',
        ),
        migrations.AlterField(
            model_name='result',
            name='group',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='exam', chained_model_field='exam', null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Group'),
        ),
    ]
