# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-15 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_auto_20170823_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_name_en',
            field=models.CharField(max_length=256, null=True, verbose_name='\u0406\u043c\u2019\u044f'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name_uk',
            field=models.CharField(max_length=256, null=True, verbose_name='\u0406\u043c\u2019\u044f'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name_en',
            field=models.CharField(max_length=256, null=True, verbose_name='\u041f\u0440\u0456\u0437\u0432\u0438\u0449\u0435'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name_uk',
            field=models.CharField(max_length=256, null=True, verbose_name='\u041f\u0440\u0456\u0437\u0432\u0438\u0449\u0435'),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name_en',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='\u041f\u043e-\u0431\u0430\u0442\u044c\u043a\u043e\u0432\u0456'),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name_uk',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='\u041f\u043e-\u0431\u0430\u0442\u044c\u043a\u043e\u0432\u0456'),
        ),
        migrations.AddField(
            model_name='student',
            name='notes_en',
            field=models.TextField(blank=True, null=True, verbose_name='\u0414\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0456 \u043d\u043e\u0442\u0430\u0442\u043a\u0438'),
        ),
        migrations.AddField(
            model_name='student',
            name='notes_uk',
            field=models.TextField(blank=True, null=True, verbose_name='\u0414\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0456 \u043d\u043e\u0442\u0430\u0442\u043a\u0438'),
        ),
    ]
