# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-16 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_auto_20170915_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='notes_en',
            field=models.TextField(blank=True, null=True, verbose_name='\u0414\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0456 \u043d\u043e\u0442\u0430\u0442\u043a\u0438'),
        ),
        migrations.AddField(
            model_name='group',
            name='notes_uk',
            field=models.TextField(blank=True, null=True, verbose_name='\u0414\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0456 \u043d\u043e\u0442\u0430\u0442\u043a\u0438'),
        ),
        migrations.AddField(
            model_name='group',
            name='title_en',
            field=models.CharField(max_length=256, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='group',
            name='title_uk',
            field=models.CharField(max_length=256, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430'),
        ),
    ]
