# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-16 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_auto_20170916_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='notes_en',
        ),
        migrations.RemoveField(
            model_name='group',
            name='notes_uk',
        ),
    ]
