# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-18 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_auto_20170918_0930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Exam', 'verbose_name_plural': 'Exams'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='monthjournal',
            options={'verbose_name': 'Monthly Journal', 'verbose_name_plural': 'Monthly Journals'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': 'Result', 'verbose_name_plural': 'Results'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Date and Time'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='teacher',
            field=models.CharField(max_length=256, verbose_name='Teacher'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='teacher_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Teacher'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='teacher_uk',
            field=models.CharField(max_length=256, null=True, verbose_name='Teacher'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Title of Subject'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Title of Subject'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title_uk',
            field=models.CharField(max_length=256, null=True, verbose_name='Title of Subject'),
        ),
        migrations.AlterField(
            model_name='group',
            name='leader',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.Student', verbose_name='Leader'),
        ),
        migrations.AlterField(
            model_name='group',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title_uk',
            field=models.CharField(max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student', unique_for_month=b'date', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='result',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.Exam', verbose_name='Exam'),
        ),
        migrations.AlterField(
            model_name='result',
            name='grade',
            field=models.FloatField(blank=True, null=True, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=256, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name_en',
            field=models.CharField(max_length=256, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name_uk',
            field=models.CharField(max_length=256, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=256, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name_uk',
            field=models.CharField(max_length=256, null=True, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name_en',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name_uk',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ticket',
            field=models.CharField(max_length=256, verbose_name='Ticket'),
        ),
    ]
