# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-21 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_auto_20170918_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='teacher_es',
            field=models.CharField(max_length=256, null=True, verbose_name='Teacher'),
        ),
        migrations.AddField(
            model_name='exam',
            name='title_es',
            field=models.CharField(max_length=256, null=True, verbose_name='Title of Subject'),
        ),
        migrations.AddField(
            model_name='group',
            name='title_es',
            field=models.CharField(max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name_es',
            field=models.CharField(max_length=256, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name_es',
            field=models.CharField(max_length=256, null=True, verbose_name='Surname'),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name_es',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Middle Name'),
        ),
    ]
